// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "main.hpp"

// tests for exercise 1
TEST_CASE("Test1 ", "[Find the Prime]")
{
	int n1, n2;
	int p1, p2;
	getTwoValues(n1, n2);
	p1 = getNextPrime(n1);
	p2 = getPrevPrime(n2);
	REQUIRE(p1 == 211);
	REQUIRE(p2 == 241);

	n1 = 200;
	n2 = 250;
	p1 = getNextPrime(n1);
	p2 = getPrevPrime(n2);

	REQUIRE(p1 == 211);
	REQUIRE(p2 == 241);
}
TEST_CASE("Test2 ", "[Find the Prime]")
{
	int n1, n2;
	int p1, p2;
	// getTwoValues(n1, n2);
	n1 = 1350;
	n2 = 1360;
	p1 = getNextPrime(n1);
	p2 = getPrevPrime(n2);

	REQUIRE(p1 == 1361);
	REQUIRE(p2 == 1327);
}